service: lets-delivery-test

frameworkVersion: "3" 

provider:
  name: aws
  runtime: nodejs20.x 
  region: us-east-1
  environment:
    CUSTOMERS_TABLE: CustomersTable
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1" 
    NODE_ENV: ${opt:stage, 'dev'}

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CUSTOMERS_TABLE} 
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S 
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH 
        BillingMode: PAY_PER_REQUEST 

functions:
  createCustomer:
    handler: src/handlers/createCustomer.handler 
    events:
      - http:
          path: customer
          method: post

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true 
      heapInitial: 200m
      heapMax: 1g
      migrate: true 
    seed: true
  serverless-offline:
    httpPort: 3000 

